package main

import (
	"log"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateSQL(gen, f)
		}
		return nil
	})
}

func generateSQL(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	filename := "init.sql"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("-- Code generated by protoc-gen-sql. DO NOT EDIT.")
	g.P()
	log.Printf("finished generating sql file")
	return g
}
